sudo: required
services:
  - docker

before_install:
  - docker build -t gokhankiziltepe/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gokhankiziltepe/react-test npm test

after_success:
  - docker build -t gokhankiziltepe/multi-client ./client
  - docker build -t gokhankiziltepe/multi-server ./server
  - docker build -t gokhankiziltepe/multi-worker ./worker
  - docker build -t gokhankiziltepe/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "#DOCKER_ID" -password-stdin
  - docker push gokhankiziltepe/multi-client
  - docker push gokhankiziltepe/multi-server
  - docker push gokhankiziltepe/multi-worker
  - docker push gokhankiziltepe/multi-nginx
  

